import { describe, expect, test } from "bun:test";

import type { BattleMetadata } from "../types/metadata";
import type { CombatEvent } from "../types/events";
import { createInitialState } from "../types/state";
import { createViewerModel, getFrameAtSeq } from "./model";
import { createBattleAnalytics } from "./analytics";

function buildMetadata(
  result: string | null = "victory",
  completionState: BattleMetadata["container"]["completion_state"] = "completed",
): BattleMetadata {
  return {
    schema_name: "sts2-combat-log",
    protocol_version: "0.2.0",
    schema_version: "0.1.0",
    mod_version: "0.1.0",
    battle_id: "battle:test",
    game: {
      title: "Slay the Spire 2",
      channel: "test",
      version: "0.99.1",
      build: "test-build",
      sts2_dll_hash: "dll-hash",
    },
    compat: {
      status: "verified",
      warning_codes: [],
      warning_messages: [],
    },
    recorder: {
      name: "sts2-combat-recorder",
      version: "0.1.0",
    },
    container: {
      completion_state: completionState,
    },
    battle: {
      character_id: "ironclad",
      character_name: "Ironclad",
      encounter_id: "test_encounter",
      encounter_name: "Test Encounter",
      seed: null,
      started_at: "2026-04-16T00:00:00.000Z",
      ended_at: "2026-04-16T00:01:00.000Z",
      result,
    },
  };
}

function buildAnalytics(
  events: CombatEvent[],
  metadata = buildMetadata(),
) {
  const model = createViewerModel({
    metadata,
    events,
    snapshots: new Map(),
  });
  const finalState =
    model.event_seqs.length > 0
      ? getFrameAtSeq(model, model.event_seqs[model.event_seqs.length - 1]).state
      : createInitialState();
  return createBattleAnalytics(model, finalState);
}

describe("viewer battle analytics", () => {
  test("merges same-definition cards and accumulates multi-hit damage", () => {
    const analytics = buildAnalytics([
      {
        seq: 0,
        event_type: "battle_started",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          encounter_id: "test_encounter",
          encounter_name: "Test Encounter",
          player_entity_id: "player:0",
          enemy_entity_ids: ["enemy:1"],
        },
      },
      {
        seq: 1,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "player:0",
          side: "player",
          name: "Ironclad",
          current_hp: 50,
          max_hp: 50,
          block: 0,
        },
      },
      {
        seq: 2,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "enemy:1",
          side: "enemy",
          name: "Cultist",
          current_hp: 20,
          max_hp: 20,
          block: 0,
        },
      },
      {
        seq: 3,
        event_type: "turn_started",
        turn_index: 1,
        phase: "turn_start",
        payload: {
          turn_index: 1,
          active_side: "player",
          phase: "turn_start",
        },
      },
      {
        seq: 4,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:001",
          card_def_id: "STRIKE",
          card_name: "Strike",
          owner_entity_id: "player:0",
          initial_zone: "draw",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 5,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:002",
          card_def_id: "STRIKE",
          card_name: "Strike",
          owner_entity_id: "player:0",
          initial_zone: "draw",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 6,
        event_type: "card_moved",
        turn_index: 1,
        phase: "turn_start",
        payload: {
          card_instance_id: "card:001",
          from_zone: "draw",
          to_zone: "hand",
          reason: "draw",
        },
      },
      {
        seq: 7,
        event_type: "card_play_started",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          actor_entity_id: "player:0",
          source_entity_id: "player:0",
          source_kind: "card",
          source_card_instance_id: "card:001",
          target_entity_ids: ["enemy:1"],
          card_def_id: "STRIKE",
          energy_cost_paid: 1,
        },
      },
      {
        seq: 8,
        event_type: "card_moved",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          from_zone: "hand",
          to_zone: "play",
          reason: "manual_play",
        },
      },
      {
        seq: 9,
        event_type: "damage_attempt",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          attempt_id: "atk_1",
          attempt_group_id: "grp_1",
          delivery_kind: "attack_root",
          original_target_entity_id: "enemy:1",
          settled_target_entity_id: "enemy:1",
          base_amount: 4,
          damage_after_damage_stage: 4,
          blocked_amount: 0,
          hp_loss: 4,
          overkill_amount: 0,
          final_settled_damage: 4,
          bypasses_block: false,
          is_powered_damage: false,
          is_move_damage: true,
          was_fully_blocked: false,
          was_block_broken: false,
          target_died: false,
          executor: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
            model_id: "STRIKE",
          },
          steps: [],
        },
      },
      {
        seq: 10,
        event_type: "hp_changed",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          entity_id: "enemy:1",
          old: 20,
          new: 16,
          delta: -4,
          reason: "damage",
        },
      },
      {
        seq: 11,
        event_type: "damage_attempt",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          attempt_id: "atk_2",
          attempt_group_id: "grp_1",
          delivery_kind: "attack_root",
          original_target_entity_id: "enemy:1",
          settled_target_entity_id: "enemy:1",
          base_amount: 5,
          damage_after_damage_stage: 5,
          blocked_amount: 0,
          hp_loss: 5,
          overkill_amount: 0,
          final_settled_damage: 5,
          bypasses_block: false,
          is_powered_damage: false,
          is_move_damage: true,
          was_fully_blocked: false,
          was_block_broken: false,
          target_died: false,
          executor: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
            model_id: "STRIKE",
          },
          steps: [],
        },
      },
      {
        seq: 12,
        event_type: "hp_changed",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          entity_id: "enemy:1",
          old: 16,
          new: 11,
          delta: -5,
          reason: "damage",
        },
      },
      {
        seq: 13,
        event_type: "card_moved",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          from_zone: "play",
          to_zone: "discard",
          reason: "resolve_play",
        },
      },
      {
        seq: 14,
        event_type: "card_play_resolved",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          final_zone: "discard",
        },
      },
    ] as CombatEvent[]);

    expect(analytics.cards).toHaveLength(1);
    expect(analytics.cards[0].card_def_id).toBe("STRIKE");
    expect(analytics.cards[0].copies_seen).toBe(2);
    expect(analytics.cards[0].times_played).toBe(1);
    expect(analytics.cards[0].damage_total).toBe(9);
    expect(analytics.cards[0].instances[0].plays[0].damage_total).toBe(9);
  });

  test("attributes block, power, generated cards, and keeps zero-contribution player cards", () => {
    const analytics = buildAnalytics([
      {
        seq: 0,
        event_type: "battle_started",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          encounter_id: "test_encounter",
          encounter_name: "Test Encounter",
          player_entity_id: "player:0",
          enemy_entity_ids: ["enemy:1"],
        },
      },
      {
        seq: 1,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "player:0",
          side: "player",
          name: "Ironclad",
          current_hp: 50,
          max_hp: 50,
          block: 0,
        },
      },
      {
        seq: 2,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "enemy:1",
          side: "enemy",
          name: "Cultist",
          current_hp: 20,
          max_hp: 20,
          block: 0,
        },
      },
      {
        seq: 3,
        event_type: "turn_started",
        turn_index: 1,
        phase: "turn_start",
        payload: {
          turn_index: 1,
          active_side: "player",
          phase: "turn_start",
        },
      },
      {
        seq: 4,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:001",
          card_def_id: "RALLY",
          card_name: "Rally",
          owner_entity_id: "player:0",
          initial_zone: "hand",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 5,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:002",
          card_def_id: "DEFEND",
          card_name: "Defend",
          owner_entity_id: "player:0",
          initial_zone: "hand",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 6,
        event_type: "card_play_started",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          actor_entity_id: "player:0",
          source_entity_id: "player:0",
          source_kind: "card",
          source_card_instance_id: "card:001",
          target_entity_ids: ["player:0"],
          card_def_id: "RALLY",
          energy_cost_paid: 1,
        },
      },
      {
        seq: 7,
        event_type: "power_applied",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          target_entity_id: "player:0",
          power_id: "METALLICIZE",
          power_name: "Metallicize",
          stacks: 2,
          trigger: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
            model_id: "RALLY",
          },
        },
      },
      {
        seq: 8,
        event_type: "card_created",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:003",
          card_def_id: "SLIMED",
          card_name: "Slimed",
          owner_entity_id: "player:0",
          initial_zone: "discard",
          cost: 1,
          created_this_combat: true,
          temporary: false,
          trigger: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
            model_id: "RALLY",
          },
        },
      },
      {
        seq: 9,
        event_type: "card_play_resolved",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          final_zone: "discard",
        },
      },
      {
        seq: 10,
        event_type: "card_play_started",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_002",
        payload: {
          card_instance_id: "card:002",
          actor_entity_id: "player:0",
          source_entity_id: "player:0",
          source_kind: "card",
          source_card_instance_id: "card:002",
          target_entity_ids: ["player:0"],
          card_def_id: "DEFEND",
          energy_cost_paid: 1,
        },
      },
      {
        seq: 11,
        event_type: "block_changed",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_002",
        payload: {
          entity_id: "player:0",
          old: 0,
          new: 8,
          delta: 8,
          reason: "block_gain",
          final_gain_amount: 8,
          trigger: {
            kind: "card_instance",
            ref: "card:002",
            card_instance_id: "card:002",
            owner_entity_id: "player:0",
            model_id: "DEFEND",
          },
        },
      },
      {
        seq: 12,
        event_type: "card_play_resolved",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_002",
        payload: {
          card_instance_id: "card:002",
          final_zone: "discard",
        },
      },
    ] as CombatEvent[]);

    expect(analytics.cards.map((card) => card.card_def_id)).toEqual([
      "RALLY",
      "DEFEND",
      "SLIMED",
    ]);
    expect(analytics.cards[0].power_events).toBe(1);
    expect(analytics.cards[0].power_stacks).toBe(2);
    expect(analytics.cards[0].generated_cards).toBe(1);
    expect(analytics.cards[1].block_total).toBe(8);
    expect(analytics.cards[2].contribution_score).toBe(0);
  });

  test("builds summary leaders and collapse-turn heuristic", () => {
    const analytics = buildAnalytics([
      {
        seq: 0,
        event_type: "battle_started",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          encounter_id: "test_encounter",
          encounter_name: "Test Encounter",
          player_entity_id: "player:0",
          enemy_entity_ids: ["enemy:1"],
        },
      },
      {
        seq: 1,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "player:0",
          side: "player",
          name: "Ironclad",
          current_hp: 40,
          max_hp: 40,
          block: 0,
        },
      },
      {
        seq: 2,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "enemy:1",
          side: "enemy",
          name: "Louse",
          current_hp: 20,
          max_hp: 20,
          block: 0,
        },
      },
      {
        seq: 3,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:001",
          card_def_id: "STRIKE",
          card_name: "Strike",
          owner_entity_id: "player:0",
          initial_zone: "hand",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 4,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:002",
          card_def_id: "DEFEND",
          card_name: "Defend",
          owner_entity_id: "player:0",
          initial_zone: "hand",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 5,
        event_type: "turn_started",
        turn_index: 1,
        phase: "turn_start",
        payload: {
          turn_index: 1,
          active_side: "player",
          phase: "turn_start",
        },
      },
      {
        seq: 6,
        event_type: "card_play_started",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          actor_entity_id: "player:0",
          source_entity_id: "player:0",
          source_kind: "card",
          source_card_instance_id: "card:001",
          target_entity_ids: ["enemy:1"],
          card_def_id: "STRIKE",
          energy_cost_paid: 1,
        },
      },
      {
        seq: 7,
        event_type: "damage_attempt",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          attempt_id: "atk_1",
          attempt_group_id: "grp_1",
          delivery_kind: "attack_root",
          original_target_entity_id: "enemy:1",
          settled_target_entity_id: "enemy:1",
          base_amount: 6,
          damage_after_damage_stage: 6,
          blocked_amount: 0,
          hp_loss: 6,
          overkill_amount: 0,
          final_settled_damage: 6,
          bypasses_block: false,
          is_powered_damage: false,
          is_move_damage: true,
          was_fully_blocked: false,
          was_block_broken: false,
          target_died: false,
          executor: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
            model_id: "STRIKE",
          },
          steps: [],
        },
      },
      {
        seq: 8,
        event_type: "hp_changed",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          entity_id: "enemy:1",
          old: 20,
          new: 14,
          delta: -6,
          reason: "damage",
        },
      },
      {
        seq: 9,
        event_type: "card_play_started",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_002",
        payload: {
          card_instance_id: "card:002",
          actor_entity_id: "player:0",
          source_entity_id: "player:0",
          source_kind: "card",
          source_card_instance_id: "card:002",
          target_entity_ids: ["player:0"],
          card_def_id: "DEFEND",
          energy_cost_paid: 1,
        },
      },
      {
        seq: 10,
        event_type: "block_changed",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_002",
        payload: {
          entity_id: "player:0",
          old: 0,
          new: 5,
          delta: 5,
          reason: "block_gain",
          final_gain_amount: 5,
          trigger: {
            kind: "card_instance",
            ref: "card:002",
            card_instance_id: "card:002",
            owner_entity_id: "player:0",
            model_id: "DEFEND",
          },
        },
      },
      {
        seq: 11,
        event_type: "turn_started",
        turn_index: 1,
        phase: "enemy_action",
        payload: {
          turn_index: 1,
          active_side: "enemy",
          phase: "enemy_action",
        },
      },
      {
        seq: 12,
        event_type: "damage_attempt",
        turn_index: 1,
        phase: "enemy_action",
        resolution_id: "r_enemy_001",
        payload: {
          attempt_id: "atk_enemy_1",
          attempt_group_id: "grp_e1",
          delivery_kind: "attack_root",
          actor_entity_id: "enemy:1",
          original_target_entity_id: "player:0",
          settled_target_entity_id: "player:0",
          base_amount: 3,
          damage_after_damage_stage: 3,
          blocked_amount: 3,
          hp_loss: 0,
          overkill_amount: 0,
          final_settled_damage: 0,
          bypasses_block: false,
          is_powered_damage: false,
          is_move_damage: true,
          was_fully_blocked: true,
          was_block_broken: false,
          target_died: false,
          executor: {
            kind: "enemy_move",
            ref: "move:enemy:1:PECK",
            owner_entity_id: "enemy:1",
            move_id: "PECK",
          },
          steps: [],
        },
      },
      {
        seq: 13,
        event_type: "block_changed",
        turn_index: 1,
        phase: "enemy_action",
        resolution_id: "r_enemy_001",
        payload: {
          entity_id: "player:0",
          old: 5,
          new: 2,
          delta: -3,
          reason: "damage_absorption",
          trigger: {
            kind: "enemy_move",
            ref: "move:enemy:1:PECK",
            owner_entity_id: "enemy:1",
            move_id: "PECK",
          },
        },
      },
      {
        seq: 14,
        event_type: "turn_started",
        turn_index: 2,
        phase: "turn_start",
        payload: {
          turn_index: 2,
          active_side: "player",
          phase: "turn_start",
        },
      },
      {
        seq: 15,
        event_type: "turn_started",
        turn_index: 2,
        phase: "enemy_action",
        payload: {
          turn_index: 2,
          active_side: "enemy",
          phase: "enemy_action",
        },
      },
      {
        seq: 16,
        event_type: "damage_attempt",
        turn_index: 2,
        phase: "enemy_action",
        resolution_id: "r_enemy_002",
        payload: {
          attempt_id: "atk_enemy_2",
          attempt_group_id: "grp_e2",
          delivery_kind: "attack_root",
          actor_entity_id: "enemy:1",
          original_target_entity_id: "player:0",
          settled_target_entity_id: "player:0",
          base_amount: 8,
          damage_after_damage_stage: 8,
          blocked_amount: 0,
          hp_loss: 8,
          overkill_amount: 0,
          final_settled_damage: 8,
          bypasses_block: false,
          is_powered_damage: false,
          is_move_damage: true,
          was_fully_blocked: false,
          was_block_broken: false,
          target_died: false,
          executor: {
            kind: "enemy_move",
            ref: "move:enemy:1:BITE",
            owner_entity_id: "enemy:1",
            move_id: "BITE",
          },
          steps: [],
        },
      },
      {
        seq: 17,
        event_type: "hp_changed",
        turn_index: 2,
        phase: "enemy_action",
        resolution_id: "r_enemy_002",
        payload: {
          entity_id: "player:0",
          old: 40,
          new: 32,
          delta: -8,
          reason: "damage",
        },
      },
      {
        seq: 18,
        event_type: "power_applied",
        turn_index: 2,
        phase: "enemy_action",
        resolution_id: "r_enemy_002",
        payload: {
          target_entity_id: "player:0",
          power_id: "VULNERABLE",
          power_name: "Vulnerable",
          stacks: 2,
          trigger: {
            kind: "enemy_move",
            ref: "move:enemy:1:BITE",
            owner_entity_id: "enemy:1",
            move_id: "BITE",
          },
        },
      },
      {
        seq: 19,
        event_type: "battle_ended",
        turn_index: 2,
        phase: "battle_end",
        payload: {
          result: "victory",
          winning_side: "player",
        },
      },
    ] as CombatEvent[]);

    expect(analytics.summary.player_damage_dealt).toBe(6);
    expect(analytics.summary.player_block_gained).toBe(5);
    expect(analytics.summary.highest_damage_source?.label).toContain("Louse");
    expect(analytics.summary.highest_block_source?.label).toBe("Defend");
    expect(analytics.summary.highest_enemy_pressure_source?.label).toContain("Louse");
    expect(analytics.summary.collapse_turn?.turn_index).toBe(2);
  });

  test("builds victory terminal chain from the last killing action", () => {
    const analytics = buildAnalytics([
      {
        seq: 0,
        event_type: "battle_started",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          encounter_id: "test_encounter",
          encounter_name: "Test Encounter",
          player_entity_id: "player:0",
          enemy_entity_ids: ["enemy:1"],
        },
      },
      {
        seq: 1,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "player:0",
          side: "player",
          name: "Ironclad",
          current_hp: 30,
          max_hp: 30,
          block: 0,
        },
      },
      {
        seq: 2,
        event_type: "entity_spawned",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          entity_id: "enemy:1",
          side: "enemy",
          name: "Jaw Worm",
          current_hp: 6,
          max_hp: 6,
          block: 0,
        },
      },
      {
        seq: 3,
        event_type: "card_created",
        turn_index: 1,
        phase: "battle_start",
        payload: {
          card_instance_id: "card:001",
          card_def_id: "STRIKE",
          card_name: "Strike",
          owner_entity_id: "player:0",
          initial_zone: "hand",
          cost: 1,
          created_this_combat: false,
          temporary: false,
        },
      },
      {
        seq: 4,
        event_type: "card_play_started",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          card_instance_id: "card:001",
          actor_entity_id: "player:0",
          source_entity_id: "player:0",
          source_kind: "card",
          source_card_instance_id: "card:001",
          target_entity_ids: ["enemy:1"],
          card_def_id: "STRIKE",
          energy_cost_paid: 1,
        },
      },
      {
        seq: 5,
        event_type: "damage_attempt",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          attempt_id: "atk_1",
          attempt_group_id: "grp_1",
          delivery_kind: "attack_root",
          original_target_entity_id: "enemy:1",
          settled_target_entity_id: "enemy:1",
          base_amount: 6,
          damage_after_damage_stage: 6,
          blocked_amount: 0,
          hp_loss: 6,
          overkill_amount: 0,
          final_settled_damage: 6,
          bypasses_block: false,
          is_powered_damage: false,
          is_move_damage: true,
          was_fully_blocked: false,
          was_block_broken: false,
          target_died: true,
          executor: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
            model_id: "STRIKE",
          },
          steps: [],
        },
      },
      {
        seq: 6,
        event_type: "hp_changed",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          entity_id: "enemy:1",
          old: 6,
          new: 0,
          delta: -6,
          reason: "damage",
        },
      },
      {
        seq: 7,
        event_type: "entity_died",
        turn_index: 1,
        phase: "player_action",
        resolution_id: "r_card_001",
        payload: {
          entity_id: "enemy:1",
          reason: "damage",
          trigger: {
            kind: "card_instance",
            ref: "card:001",
            card_instance_id: "card:001",
            owner_entity_id: "player:0",
          },
        },
      },
      {
        seq: 8,
        event_type: "battle_ended",
        turn_index: 1,
        phase: "battle_end",
        payload: {
          result: "victory",
          winning_side: "player",
        },
      },
    ] as CombatEvent[]);

    expect(analytics.terminal_chain?.mode).toBe("victory");
    expect(analytics.terminal_chain?.subject_entity_id).toBe("enemy:1");
    expect(analytics.terminal_chain?.events.map((event) => event.event_type)).toEqual([
      "card_play_started",
      "damage_attempt",
      "hp_changed",
      "entity_died",
    ]);
  });

  test("builds defeat terminal chain from the killing enemy action", () => {
    const analytics = buildAnalytics(
      [
        {
          seq: 0,
          event_type: "battle_started",
          turn_index: 1,
          phase: "battle_start",
          payload: {
            encounter_id: "test_encounter",
            encounter_name: "Test Encounter",
            player_entity_id: "player:0",
            enemy_entity_ids: ["enemy:1"],
          },
        },
        {
          seq: 1,
          event_type: "entity_spawned",
          turn_index: 1,
          phase: "battle_start",
          payload: {
            entity_id: "player:0",
            side: "player",
            name: "Ironclad",
            current_hp: 4,
            max_hp: 40,
            block: 0,
          },
        },
        {
          seq: 2,
          event_type: "entity_spawned",
          turn_index: 1,
          phase: "battle_start",
          payload: {
            entity_id: "enemy:1",
            side: "enemy",
            name: "Fungi Beast",
            current_hp: 20,
            max_hp: 20,
            block: 0,
          },
        },
        {
          seq: 3,
          event_type: "turn_started",
          turn_index: 1,
          phase: "enemy_action",
          payload: {
            turn_index: 1,
            active_side: "enemy",
            phase: "enemy_action",
          },
        },
        {
          seq: 4,
          event_type: "damage_attempt",
          turn_index: 1,
          phase: "enemy_action",
          resolution_id: "r_enemy_001",
          payload: {
            attempt_id: "atk_1",
            attempt_group_id: "grp_1",
            delivery_kind: "attack_root",
            actor_entity_id: "enemy:1",
            original_target_entity_id: "player:0",
            settled_target_entity_id: "player:0",
            base_amount: 7,
            damage_after_damage_stage: 7,
            blocked_amount: 0,
            hp_loss: 4,
            overkill_amount: 3,
            final_settled_damage: 7,
            bypasses_block: false,
            is_powered_damage: false,
            is_move_damage: true,
            was_fully_blocked: false,
            was_block_broken: false,
            target_died: true,
            executor: {
              kind: "enemy_move",
              ref: "move:enemy:1:SMASH",
              owner_entity_id: "enemy:1",
              move_id: "SMASH",
            },
            steps: [],
          },
        },
        {
          seq: 5,
          event_type: "hp_changed",
          turn_index: 1,
          phase: "enemy_action",
          resolution_id: "r_enemy_001",
          payload: {
            entity_id: "player:0",
            old: 4,
            new: 0,
            delta: -4,
            reason: "damage",
          },
        },
        {
          seq: 6,
          event_type: "entity_died",
          turn_index: 1,
          phase: "enemy_action",
          resolution_id: "r_enemy_001",
          payload: {
            entity_id: "player:0",
            reason: "damage",
            trigger: {
              kind: "enemy_move",
              ref: "move:enemy:1:SMASH",
              owner_entity_id: "enemy:1",
              move_id: "SMASH",
            },
          },
        },
        {
          seq: 7,
          event_type: "battle_ended",
          turn_index: 1,
          phase: "battle_end",
          payload: {
            result: "defeat",
            winning_side: "enemy",
          },
        },
      ] as CombatEvent[],
      buildMetadata("defeat"),
    );

    expect(analytics.terminal_chain?.mode).toBe("defeat");
    expect(analytics.terminal_chain?.subject_entity_id).toBe("player:0");
    expect(analytics.terminal_chain?.events.map((event) => event.event_type)).toEqual([
      "damage_attempt",
      "hp_changed",
      "entity_died",
    ]);
  });

  test("marks partial unknown battles as provisional and keeps zero-contribution cards", () => {
    const analytics = buildAnalytics(
      [
        {
          seq: 0,
          event_type: "battle_started",
          turn_index: 1,
          phase: "battle_start",
          payload: {
            encounter_id: "test_encounter",
            encounter_name: "Test Encounter",
            player_entity_id: "player:0",
            enemy_entity_ids: ["enemy:1"],
          },
        },
        {
          seq: 1,
          event_type: "entity_spawned",
          turn_index: 1,
          phase: "battle_start",
          payload: {
            entity_id: "player:0",
            side: "player",
            name: "Ironclad",
            current_hp: 30,
            max_hp: 30,
            block: 0,
          },
        },
        {
          seq: 2,
          event_type: "card_created",
          turn_index: 1,
          phase: "battle_start",
          payload: {
            card_instance_id: "card:001",
            card_def_id: "STATUS_CURSE",
            card_name: "Status Curse",
            owner_entity_id: "player:0",
            initial_zone: "draw",
            cost: 1,
            created_this_combat: true,
            temporary: false,
          },
        },
      ] as CombatEvent[],
      buildMetadata("unknown", "partial"),
    );

    expect(analytics.summary.is_provisional).toBe(true);
    expect(analytics.cards).toHaveLength(1);
    expect(analytics.cards[0].contribution_score).toBe(0);
  });
});
